// <auto-generated />
using System;
using AnimeWorld.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeWorld.Migrations
{
    [DbContext(typeof(AnimeCharacterDbContext))]
    [Migration("20251020101755_scriptsZZ")]
    partial class scriptsZZ
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeWorld.Models.AnimeCharacter", b =>
                {
                    b.Property<int>("AnimeCharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimeCharacterId"));

                    b.Property<string>("AnimeCharacterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BankBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CharacterPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.HasKey("AnimeCharacterId");

                    b.HasIndex("GenresId");

                    b.ToTable("AnimeCharacters");
                });

            modelBuilder.Entity("AnimeWorld.Models.AnimeName", b =>
                {
                    b.Property<int>("AnimeNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimeNameId"));

                    b.Property<string>("AnimationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AnimeCharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("OnGoing")
                        .HasColumnType("bit");

                    b.Property<int>("TotalEp")
                        .HasColumnType("int");

                    b.HasKey("AnimeNameId");

                    b.HasIndex("AnimeCharacterId");

                    b.ToTable("AnimeNames");
                });

            modelBuilder.Entity("AnimeWorld.Models.Genres", b =>
                {
                    b.Property<int>("GenresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenresId"));

                    b.Property<string>("GenresName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenresId");

                    b.ToTable("Genress");
                });

            modelBuilder.Entity("AnimeWorld.Models.AnimeCharacter", b =>
                {
                    b.HasOne("AnimeWorld.Models.Genres", "Genres")
                        .WithMany("AnimeCharacters")
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("AnimeWorld.Models.AnimeName", b =>
                {
                    b.HasOne("AnimeWorld.Models.AnimeCharacter", "AnimeCharacter")
                        .WithMany("AnimeNames")
                        .HasForeignKey("AnimeCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimeCharacter");
                });

            modelBuilder.Entity("AnimeWorld.Models.AnimeCharacter", b =>
                {
                    b.Navigation("AnimeNames");
                });

            modelBuilder.Entity("AnimeWorld.Models.Genres", b =>
                {
                    b.Navigation("AnimeCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
